name: cement-strenght-prediction
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : pip3 install -r requiremt.txt
      - run : python run.py
