name: cement-strenght-prediction
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v3
      - run : pip3 install -r requirement.txt
      - run : python src/run.py --action predict
      - run: ls -a
