name: cement-strenght-prediction
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: requiements installation
      - run : pip3 install -r requirement.txt
      - name: script run
      - run : python src/run.py
      - name: print files
      - run: ls -a
